// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI/migration commands (migrate, db push, introspect) need this,
  // separately from the app runtime's pooled DATABASE_URL in lib/prisma.ts —
  // the transaction pooler (port 6543) doesn't support the advisory locks
  // Prisma Migrate needs, so pointing the CLI at it hangs with no error.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
